"""Where all the internal constants for sunsehttp reside."""

error_code_reasons = {
    400: "Request was malformed.",
    401: "Request was denied, due to being unauthorized/authenticated.",
    403: "Request was denied due to missing access rights.",
    404: "Request requested a resource that does not exist or was not found.",
    405: "Request method was known by the server, but not supported by the current resource requested.",
    406: "Request sent info that wasn't acceptable by the web server.",
    407: "Request was denied, due to not being authorized by a proxy.",
    408: "Request timed out.",
    409: "Request conflicts with the current state of the server.",
    410: "Request requested for a resource that was permanently deleted from the server.",
    411: "Request denied due to missing Content-Length header required by the server.",
    412: "Request failed due to missing preconditions from the client.",
    413: "Request body is too large.",
    414: "The URI that this request requested for is longer than the server is willing to interpret.",
    415: "Request body requested or included a unsupported media type that the server could not interpret.",
    416: "The Range header in this request can not be fulfilled.",
    417: "The Expect header in this request could not be met by the server.",
    418: "Come on, man! Too much coffee. Use the coffee library.",
    421: "The server is not able to produce a response to this request.",
    422: "The request was well formed, but was unable to be followed due to errors with HTTP semantics.",
    423: "The resource that this request wants to access is locked.",
    424: "The request failed due to the prior failing of another request.",
    425: "The server is unwilling to risk processing a request that might be replayed.",
    426: "The server wants the client (you) to upgrade to another protocol. The specified protocol is in the Upgrade header.",
    428: "The server requires this request to be conditional.",
    429: "This request (or a prior request) reached the rate limit for this server.",
    431: "This request's header fields are larger than the server's limit to process them.",
    451: "Unavailable for legal reasons.",
    500: "General Server Error. This is not the request's fault.",
    501: "This request method is not supported by the server.",
    502: "Bad Gateway. This is not the request's fault.",
    503: "The server is not ready to handle this request.",
    504: "The server reached a gateway timeout.",
    505: "This HTTP version is not supported by the server.",
    506: "Error in content negotiation in the server.",
    507: "The server is unable to store the representation/result of this request, and therefore rejecting it.",
    508: "The server detected an infinite loop when processing the request.",
    510: "The client request declares an HTTP extension, but the extension is not supported by the server.",
    511: "The client needs to authenticate to gain network access.",
}
